---
# tasks file for ec2_asg_lc_copy
- name: Find the current launch config associated with the ASG
  command: >
    aws autoscaling describe-launch-configurations
    --launch-configuration-names {{ ec2_asg_lc_copy_asg_lc_name }}
    --profile {{ ec2_asg_lc_copy_boto_profile | d(omit) }}
    --region {{ ec2_asg_lc_copy_region | d(omit) }}
    --max-items 1
  register: ec2_asg_lc_asg_stdout

- name: Convert AWS CLI output to json and store the launch configuration
  set_fact: ec2_asg_lc_current="{{ (ec2_asg_lc_asg_stdout.stdout | from_yaml).LaunchConfigurations[0] }}"

- name: Create a new Launch Configuration based on the old one with any updates
  ec2_lc:
    state: present
    name: "{{ ec2_asg_lc_current.LaunchConfigurationName }}-Copy"
    image_id: "{{ ec2_asg_lc_copy_image_id | d(ec2_asg_lc_current.ImageId) }}"
    instance_profile_name: "{{ ec2_asg_lc_copy_instance_profile | d(ec2_asg_lc_current.IamInstanceProfile) }}"
    instance_type: "{{ ec2_asg_lc_copy_instance_type | d(ec2_asg_lc_current.InstanceType) }}"
    key_name: "{{ ec2_asg_lc_copy_key_name | default(ec2_asg_lc_current.KeyName) }}"
    security_groups: "{{ ec2_asg_lc_copy_security_groups | d(ec2_asg_lc_current.SecurityGroups) }}"
    user_data: "{{ ec2_asg_lc_copy_user_data | d(ec2_asg_lc_current.UserData | b64decode) }}"
    region: "{{ ec2_asg_lc_copy_region | d(omit) }}"
    profile: "{{ ec2_asg_lc_copy_boto_profile | d(omit) }}"
  register: ec2_asg_lc_copy_new_lc

- name: Update the ASG to use the newly created launch configuration
  ec2_asg:
    name: "{{ ec2_asg_lc_copy_asg_group_name }}"
    state: present
    launch_config_name: "{{ ec2_asg_lc_copy_new_lc.name }}"
    lc_check: no
    region: "{{ ec2_asg_lc_copy_region | d(omit) }}"
    profile: "{{ ec2_asg_lc_copy_boto_profile | d(omit) }}"

- name: Remove the old launch configuration
  ec2_lc:
    state: absent
    name: "{{ ec2_asg_lc_copy_asg_lc_name }}"
    region: "{{ ec2_asg_lc_copy_region | d(omit) }}"
    profile: "{{ ec2_asg_lc_copy_boto_profile | d(omit) }}"
  when: "{{ ec2_asg_lc_copy_delete_prior_lc | bool }}"
